'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da wsdl, versione=4.6.1055.0.
'
Namespace WebService.codicefiscale
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CodiceFiscaleSoap", [Namespace]:="http://webservices.dotnethell.it/CodiceFiscale")>  _
    Partial Public Class CodiceFiscale
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CalcolaCodiceFiscaleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CodiceComuneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private NomeComuneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ControllaCodiceFiscaleOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://webservices.dotnethell.it/codicefiscale.asmx"
        End Sub
        
        '''<remarks/>
        Public Event CalcolaCodiceFiscaleCompleted As CalcolaCodiceFiscaleCompletedEventHandler
        
        '''<remarks/>
        Public Event CodiceComuneCompleted As CodiceComuneCompletedEventHandler
        
        '''<remarks/>
        Public Event NomeComuneCompleted As NomeComuneCompletedEventHandler
        
        '''<remarks/>
        Public Event ControllaCodiceFiscaleCompleted As ControllaCodiceFiscaleCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/CalcolaCodiceFiscale", RequestNamespace:="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace:="http://webservices.dotnethell.it/CodiceFiscale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcolaCodiceFiscale(ByVal Nome As String, ByVal Cognome As String, ByVal ComuneNascita As String, ByVal DataNascita As String, ByVal Sesso As String) As String
            Dim results() As Object = Me.Invoke("CalcolaCodiceFiscale", New Object() {Nome, Cognome, ComuneNascita, DataNascita, Sesso})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCalcolaCodiceFiscale(ByVal Nome As String, ByVal Cognome As String, ByVal ComuneNascita As String, ByVal DataNascita As String, ByVal Sesso As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CalcolaCodiceFiscale", New Object() {Nome, Cognome, ComuneNascita, DataNascita, Sesso}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCalcolaCodiceFiscale(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcolaCodiceFiscaleAsync(ByVal Nome As String, ByVal Cognome As String, ByVal ComuneNascita As String, ByVal DataNascita As String, ByVal Sesso As String)
            Me.CalcolaCodiceFiscaleAsync(Nome, Cognome, ComuneNascita, DataNascita, Sesso, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcolaCodiceFiscaleAsync(ByVal Nome As String, ByVal Cognome As String, ByVal ComuneNascita As String, ByVal DataNascita As String, ByVal Sesso As String, ByVal userState As Object)
            If (Me.CalcolaCodiceFiscaleOperationCompleted Is Nothing) Then
                Me.CalcolaCodiceFiscaleOperationCompleted = AddressOf Me.OnCalcolaCodiceFiscaleOperationCompleted
            End If
            Me.InvokeAsync("CalcolaCodiceFiscale", New Object() {Nome, Cognome, ComuneNascita, DataNascita, Sesso}, Me.CalcolaCodiceFiscaleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcolaCodiceFiscaleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcolaCodiceFiscaleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcolaCodiceFiscaleCompleted(Me, New CalcolaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/CodiceComune", RequestNamespace:="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace:="http://webservices.dotnethell.it/CodiceFiscale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CodiceComune(ByVal NomeComune As String) As String
            Dim results() As Object = Me.Invoke("CodiceComune", New Object() {NomeComune})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCodiceComune(ByVal NomeComune As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CodiceComune", New Object() {NomeComune}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCodiceComune(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CodiceComuneAsync(ByVal NomeComune As String)
            Me.CodiceComuneAsync(NomeComune, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CodiceComuneAsync(ByVal NomeComune As String, ByVal userState As Object)
            If (Me.CodiceComuneOperationCompleted Is Nothing) Then
                Me.CodiceComuneOperationCompleted = AddressOf Me.OnCodiceComuneOperationCompleted
            End If
            Me.InvokeAsync("CodiceComune", New Object() {NomeComune}, Me.CodiceComuneOperationCompleted, userState)
        End Sub
        
        Private Sub OnCodiceComuneOperationCompleted(ByVal arg As Object)
            If (Not (Me.CodiceComuneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CodiceComuneCompleted(Me, New CodiceComuneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/NomeComune", RequestNamespace:="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace:="http://webservices.dotnethell.it/CodiceFiscale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function NomeComune(<System.Xml.Serialization.XmlElementAttribute("CodiceComune")> ByVal CodiceComune1 As String) As String
            Dim results() As Object = Me.Invoke("NomeComune", New Object() {CodiceComune1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginNomeComune(ByVal CodiceComune1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NomeComune", New Object() {CodiceComune1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndNomeComune(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub NomeComuneAsync(ByVal CodiceComune1 As String)
            Me.NomeComuneAsync(CodiceComune1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub NomeComuneAsync(ByVal CodiceComune1 As String, ByVal userState As Object)
            If (Me.NomeComuneOperationCompleted Is Nothing) Then
                Me.NomeComuneOperationCompleted = AddressOf Me.OnNomeComuneOperationCompleted
            End If
            Me.InvokeAsync("NomeComune", New Object() {CodiceComune1}, Me.NomeComuneOperationCompleted, userState)
        End Sub
        
        Private Sub OnNomeComuneOperationCompleted(ByVal arg As Object)
            If (Not (Me.NomeComuneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NomeComuneCompleted(Me, New NomeComuneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/ControllaCodiceFiscale", RequestNamespace:="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace:="http://webservices.dotnethell.it/CodiceFiscale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ControllaCodiceFiscale(ByVal CodiceFiscale As String) As String
            Dim results() As Object = Me.Invoke("ControllaCodiceFiscale", New Object() {CodiceFiscale})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginControllaCodiceFiscale(ByVal CodiceFiscale As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ControllaCodiceFiscale", New Object() {CodiceFiscale}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndControllaCodiceFiscale(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ControllaCodiceFiscaleAsync(ByVal CodiceFiscale As String)
            Me.ControllaCodiceFiscaleAsync(CodiceFiscale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ControllaCodiceFiscaleAsync(ByVal CodiceFiscale As String, ByVal userState As Object)
            If (Me.ControllaCodiceFiscaleOperationCompleted Is Nothing) Then
                Me.ControllaCodiceFiscaleOperationCompleted = AddressOf Me.OnControllaCodiceFiscaleOperationCompleted
            End If
            Me.InvokeAsync("ControllaCodiceFiscale", New Object() {CodiceFiscale}, Me.ControllaCodiceFiscaleOperationCompleted, userState)
        End Sub
        
        Private Sub OnControllaCodiceFiscaleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ControllaCodiceFiscaleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ControllaCodiceFiscaleCompleted(Me, New ControllaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
    Public Delegate Sub CalcolaCodiceFiscaleCompletedEventHandler(ByVal sender As Object, ByVal e As CalcolaCodiceFiscaleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcolaCodiceFiscaleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
    Public Delegate Sub CodiceComuneCompletedEventHandler(ByVal sender As Object, ByVal e As CodiceComuneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CodiceComuneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
    Public Delegate Sub NomeComuneCompletedEventHandler(ByVal sender As Object, ByVal e As NomeComuneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class NomeComuneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
    Public Delegate Sub ControllaCodiceFiscaleCompletedEventHandler(ByVal sender As Object, ByVal e As ControllaCodiceFiscaleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ControllaCodiceFiscaleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
