'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace GetCognomSocio
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GetCognomSocio.GetinfocognomnomSociSoap")>  _
    Public Interface GetinfocognomnomSociSoap
        
        'CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento codiceFiscale dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInfoSoci", ReplyAction:="*")>  _
        Function GetInfoSoci(ByVal request As GetCognomSocio.GetInfoSociRequest) As GetCognomSocio.GetInfoSociResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInfoSoci", ReplyAction:="*")>  _
        Function GetInfoSociAsync(ByVal request As GetCognomSocio.GetInfoSociRequest) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoSociResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento GetInfoUserByIdSocioResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInfoUserByIdSocio", ReplyAction:="*")>  _
        Function GetInfoUserByIdSocio(ByVal request As GetCognomSocio.GetInfoUserByIdSocioRequest) As GetCognomSocio.GetInfoUserByIdSocioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInfoUserByIdSocio", ReplyAction:="*")>  _
        Function GetInfoUserByIdSocioAsync(ByVal request As GetCognomSocio.GetInfoUserByIdSocioRequest) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoUserByIdSocioResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoSociRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoSoci", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GetCognomSocio.GetInfoSociRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GetCognomSocio.GetInfoSociRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetInfoSociRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public codiceFiscale As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal codiceFiscale As String)
            MyBase.New
            Me.codiceFiscale = codiceFiscale
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoSociResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoSociResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GetCognomSocio.GetInfoSociResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GetCognomSocio.GetInfoSociResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetInfoSociResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetInfoSociResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetInfoSociResult As String)
            MyBase.New
            Me.GetInfoSociResult = GetInfoSociResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoUserByIdSocioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoUserByIdSocio", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GetCognomSocio.GetInfoUserByIdSocioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GetCognomSocio.GetInfoUserByIdSocioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetInfoUserByIdSocioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idsocio As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idsocio As Integer)
            MyBase.New
            Me.idsocio = idsocio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoUserByIdSocioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoUserByIdSocioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As GetCognomSocio.GetInfoUserByIdSocioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As GetCognomSocio.GetInfoUserByIdSocioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetInfoUserByIdSocioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetInfoUserByIdSocioResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetInfoUserByIdSocioResult As String)
            MyBase.New
            Me.GetInfoUserByIdSocioResult = GetInfoUserByIdSocioResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface GetinfocognomnomSociSoapChannel
        Inherits GetCognomSocio.GetinfocognomnomSociSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetinfocognomnomSociSoapClient
        Inherits System.ServiceModel.ClientBase(Of GetCognomSocio.GetinfocognomnomSociSoap)
        Implements GetCognomSocio.GetinfocognomnomSociSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetCognomSocio_GetinfocognomnomSociSoap_GetInfoSoci(ByVal request As GetCognomSocio.GetInfoSociRequest) As GetCognomSocio.GetInfoSociResponse Implements GetCognomSocio.GetinfocognomnomSociSoap.GetInfoSoci
            Return MyBase.Channel.GetInfoSoci(request)
        End Function
        
        Public Function GetInfoSoci(ByVal codiceFiscale As String) As String
            Dim inValue As GetCognomSocio.GetInfoSociRequest = New GetCognomSocio.GetInfoSociRequest()
            inValue.Body = New GetCognomSocio.GetInfoSociRequestBody()
            inValue.Body.codiceFiscale = codiceFiscale
            Dim retVal As GetCognomSocio.GetInfoSociResponse = CType(Me,GetCognomSocio.GetinfocognomnomSociSoap).GetInfoSoci(inValue)
            Return retVal.Body.GetInfoSociResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetCognomSocio_GetinfocognomnomSociSoap_GetInfoSociAsync(ByVal request As GetCognomSocio.GetInfoSociRequest) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoSociResponse) Implements GetCognomSocio.GetinfocognomnomSociSoap.GetInfoSociAsync
            Return MyBase.Channel.GetInfoSociAsync(request)
        End Function
        
        Public Function GetInfoSociAsync(ByVal codiceFiscale As String) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoSociResponse)
            Dim inValue As GetCognomSocio.GetInfoSociRequest = New GetCognomSocio.GetInfoSociRequest()
            inValue.Body = New GetCognomSocio.GetInfoSociRequestBody()
            inValue.Body.codiceFiscale = codiceFiscale
            Return CType(Me,GetCognomSocio.GetinfocognomnomSociSoap).GetInfoSociAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetCognomSocio_GetinfocognomnomSociSoap_GetInfoUserByIdSocio(ByVal request As GetCognomSocio.GetInfoUserByIdSocioRequest) As GetCognomSocio.GetInfoUserByIdSocioResponse Implements GetCognomSocio.GetinfocognomnomSociSoap.GetInfoUserByIdSocio
            Return MyBase.Channel.GetInfoUserByIdSocio(request)
        End Function
        
        Public Function GetInfoUserByIdSocio(ByVal idsocio As Integer) As String
            Dim inValue As GetCognomSocio.GetInfoUserByIdSocioRequest = New GetCognomSocio.GetInfoUserByIdSocioRequest()
            inValue.Body = New GetCognomSocio.GetInfoUserByIdSocioRequestBody()
            inValue.Body.idsocio = idsocio
            Dim retVal As GetCognomSocio.GetInfoUserByIdSocioResponse = CType(Me,GetCognomSocio.GetinfocognomnomSociSoap).GetInfoUserByIdSocio(inValue)
            Return retVal.Body.GetInfoUserByIdSocioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetCognomSocio_GetinfocognomnomSociSoap_GetInfoUserByIdSocioAsync(ByVal request As GetCognomSocio.GetInfoUserByIdSocioRequest) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoUserByIdSocioResponse) Implements GetCognomSocio.GetinfocognomnomSociSoap.GetInfoUserByIdSocioAsync
            Return MyBase.Channel.GetInfoUserByIdSocioAsync(request)
        End Function
        
        Public Function GetInfoUserByIdSocioAsync(ByVal idsocio As Integer) As System.Threading.Tasks.Task(Of GetCognomSocio.GetInfoUserByIdSocioResponse)
            Dim inValue As GetCognomSocio.GetInfoUserByIdSocioRequest = New GetCognomSocio.GetInfoUserByIdSocioRequest()
            inValue.Body = New GetCognomSocio.GetInfoUserByIdSocioRequestBody()
            inValue.Body.idsocio = idsocio
            Return CType(Me,GetCognomSocio.GetinfocognomnomSociSoap).GetInfoUserByIdSocioAsync(inValue)
        End Function
    End Class
End Namespace
