'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WebServicegna
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="codfisc", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class codfisc
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codicefiscaleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codiceesteroField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property codicefiscale() As String
            Get
                Return Me.codicefiscaleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codicefiscaleField, value) <> true) Then
                    Me.codicefiscaleField = value
                    Me.RaisePropertyChanged("codicefiscale")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property codiceestero() As String
            Get
                Return Me.codiceesteroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codiceesteroField, value) <> true) Then
                    Me.codiceesteroField = value
                    Me.RaisePropertyChanged("codiceestero")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WebServicegna.CalcoloCodiceFiscaleSoap")>  _
    Public Interface CalcoloCodiceFiscaleSoap
        
        'CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento nome dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/calcolocodicefiscaleV2", ReplyAction:="*")>  _
        Function calcolocodicefiscaleV2(ByVal request As WebServicegna.calcolocodicefiscaleV2Request) As WebServicegna.calcolocodicefiscaleV2Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/calcolocodicefiscaleV2", ReplyAction:="*")>  _
        Function calcolocodicefiscaleV2Async(ByVal request As WebServicegna.calcolocodicefiscaleV2Request) As System.Threading.Tasks.Task(Of WebServicegna.calcolocodicefiscaleV2Response)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcolocodicefiscaleV2Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcolocodicefiscaleV2", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServicegna.calcolocodicefiscaleV2RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServicegna.calcolocodicefiscaleV2RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class calcolocodicefiscaleV2RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nome As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cognome As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public datanascita As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public comunenascita As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public sesso As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nome As String, ByVal cognome As String, ByVal datanascita As String, ByVal comunenascita As String, ByVal sesso As String)
            MyBase.New
            Me.nome = nome
            Me.cognome = cognome
            Me.datanascita = datanascita
            Me.comunenascita = comunenascita
            Me.sesso = sesso
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class calcolocodicefiscaleV2Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="calcolocodicefiscaleV2Response", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WebServicegna.calcolocodicefiscaleV2ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServicegna.calcolocodicefiscaleV2ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class calcolocodicefiscaleV2ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public calcolocodicefiscaleV2Result As WebServicegna.codfisc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal calcolocodicefiscaleV2Result As WebServicegna.codfisc)
            MyBase.New
            Me.calcolocodicefiscaleV2Result = calcolocodicefiscaleV2Result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalcoloCodiceFiscaleSoapChannel
        Inherits WebServicegna.CalcoloCodiceFiscaleSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalcoloCodiceFiscaleSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServicegna.CalcoloCodiceFiscaleSoap)
        Implements WebServicegna.CalcoloCodiceFiscaleSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServicegna_CalcoloCodiceFiscaleSoap_calcolocodicefiscaleV2(ByVal request As WebServicegna.calcolocodicefiscaleV2Request) As WebServicegna.calcolocodicefiscaleV2Response Implements WebServicegna.CalcoloCodiceFiscaleSoap.calcolocodicefiscaleV2
            Return MyBase.Channel.calcolocodicefiscaleV2(request)
        End Function
        
        Public Function calcolocodicefiscaleV2(ByVal nome As String, ByVal cognome As String, ByVal datanascita As String, ByVal comunenascita As String, ByVal sesso As String) As WebServicegna.codfisc
            Dim inValue As WebServicegna.calcolocodicefiscaleV2Request = New WebServicegna.calcolocodicefiscaleV2Request()
            inValue.Body = New WebServicegna.calcolocodicefiscaleV2RequestBody()
            inValue.Body.nome = nome
            inValue.Body.cognome = cognome
            inValue.Body.datanascita = datanascita
            inValue.Body.comunenascita = comunenascita
            inValue.Body.sesso = sesso
            Dim retVal As WebServicegna.calcolocodicefiscaleV2Response = CType(Me,WebServicegna.CalcoloCodiceFiscaleSoap).calcolocodicefiscaleV2(inValue)
            Return retVal.Body.calcolocodicefiscaleV2Result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServicegna_CalcoloCodiceFiscaleSoap_calcolocodicefiscaleV2Async(ByVal request As WebServicegna.calcolocodicefiscaleV2Request) As System.Threading.Tasks.Task(Of WebServicegna.calcolocodicefiscaleV2Response) Implements WebServicegna.CalcoloCodiceFiscaleSoap.calcolocodicefiscaleV2Async
            Return MyBase.Channel.calcolocodicefiscaleV2Async(request)
        End Function
        
        Public Function calcolocodicefiscaleV2Async(ByVal nome As String, ByVal cognome As String, ByVal datanascita As String, ByVal comunenascita As String, ByVal sesso As String) As System.Threading.Tasks.Task(Of WebServicegna.calcolocodicefiscaleV2Response)
            Dim inValue As WebServicegna.calcolocodicefiscaleV2Request = New WebServicegna.calcolocodicefiscaleV2Request()
            inValue.Body = New WebServicegna.calcolocodicefiscaleV2RequestBody()
            inValue.Body.nome = nome
            inValue.Body.cognome = cognome
            inValue.Body.datanascita = datanascita
            inValue.Body.comunenascita = comunenascita
            inValue.Body.sesso = sesso
            Return CType(Me,WebServicegna.CalcoloCodiceFiscaleSoap).calcolocodicefiscaleV2Async(inValue)
        End Function
    End Class
End Namespace
