'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class registrazioneDroni
    
    '''<summary>
    '''listacorsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents listacorsi As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_cognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_cognome As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_nome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_nome As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_datanascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_datanascita As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''listacomuni_ctl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents listacomuni_ctl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtprov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txtprov As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_indirizzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_indirizzo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_civico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_civico As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''listacity_ctl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents listacity_ctl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''listacap_ctl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents listacap_ctl As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_prov_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_prov_res As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txt_codicefiscale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_codicefiscale As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''listatipodocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents listatipodocumento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_numerodoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_numerodoc As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''data_rilascio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents data_rilascio As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''data_scadenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents data_scadenza As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''enterilascio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents enterilascio As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''luogorilascio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents luogorilascio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtmobilenumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txtmobilenumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtmobilnumberuff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txtmobilnumberuff As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttelefonoab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txttelefonoab As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttelefonouff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txttelefonouff As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txtemail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtemailuff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txtemailuff As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttitolostudio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txttitolostudio As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents gna As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''mininterno_poliziastato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents mininterno_poliziastato As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''mindifesa_carabinieri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents mindifesa_carabinieri As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''minfinanze_guardiafinanza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents minfinanze_guardiafinanza As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PCDM_protezionecivile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents PCDM_protezionecivile As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''vigilifuoco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents vigilifuoco As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''poliziamunicipale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents poliziamunicipale As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''associazionepolstato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents associazionepolstato As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''associazioneNazCarabinieri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents associazioneNazCarabinieri As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''associazionenazfinanzieri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents associazionenazfinanzieri As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''mingiustizia_poliziaPenitenziaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents mingiustizia_poliziaPenitenziaria As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''altrienti_azienda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents altrienti_azienda As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txt_altro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents txt_altro As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sezmatr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents sezmatr As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''inputmatr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents inputmatr As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''matricola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents matricola As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sezcred control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents sezcred As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''inputcred_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents inputcred_user As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''user_id_corsista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents user_id_corsista As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''inputcred_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents inputcred_password As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''pwd_corsista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents pwd_corsista As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''basico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents basico As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''critico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents critico As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''soluzione_completa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents soluzione_completa As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Modalità1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Modalità1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Modalità2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Modalità2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Modalità3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents Modalità3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents SI As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents NO As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''errore_successo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents errore_successo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btn_registra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents btn_registra As Global.System.Web.UI.WebControls.ImageButton
End Class
